import { City } from "../../types";

const mockCityData: City[] = [
  {
    id: 1,
    name: "Madison",
    lat: "43.0752983",
    lng: "-89.393898",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/madison-wi",
  },
  {
    id: 2,
    name: "Milwaukee",
    lat: "43.028801",
    lng: "-87.9720001",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/milwaukee-wi",
  },
  {
    id: 3,
    name: "Madison",
    lat: "0.00",
    lng: "0.00",
    state_name: "Alabama",
    state_abrv: "AL",
    url: "https://www.rentable.co/",
  },
  {
    id: 122,
    name: "Bridgeport",
    lat: "41.16",
    lng: "-73.2",
    state_name: "Connecticut",
    state_abrv: "CT",
    url: "https://www.rentable.co/bridgeport-ct",
  },
  {
    id: 571,
    name: "Jackson",
    lat: "43.32",
    lng: "-88.16",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/jackson-wi",
  },
  {
    id: 572,
    name: "Port Washington",
    lat: "43.38",
    lng: "-87.87",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/port-washington-wi",
  },
  {
    id: 573,
    name: "Portage",
    lat: "43.53",
    lng: "-89.46",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/portage-wi",
  },
  {
    id: 574,
    name: "Middleton",
    lat: "43.09",
    lng: "-89.5",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/middleton-wi",
  },
  {
    id: 575,
    name: "Kaukauna",
    lat: "44.27",
    lng: "-88.27",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/kaukauna-wi",
  },
  {
    id: 576,
    name: "Chippewa Falls",
    lat: "44.93",
    lng: "-91.39",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/chippewa-falls-wi",
  },
  {
    id: 577,
    name: "Prescott",
    lat: "44.74",
    lng: "-92.8",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/prescott-wi",
  },
  {
    id: 578,
    name: "Stoughton",
    lat: "42.91",
    lng: "-89.21",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/stoughton-wi",
  },
  {
    id: 579,
    name: "Racine",
    lat: "42.72",
    lng: "-87.78",
    state_name: "Wisconsin",
    state_abrv: "WI",
    url: "https://www.rentable.co/racine-wi",
  },
];

export default mockCityData;
